version: '3.7'

networks:
  carbon-net:

services:
  # ---------------- Orderer ----------------
  orderer.carbon.com:
    container_name: orderer.carbon.com
    image: hyperledger/fabric-orderer:2.5.13
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./organizations/ordererOrganizations/carbon.com/orderers/orderer.carbon.com/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/carbon.com/orderers/orderer.carbon.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - carbon-net

  # ---------------- CouchDB for Seller ----------------
  couchdb0.seller:
    container_name: couchdb0.seller
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - carbon-net

  couchdb1.seller:
    container_name: couchdb1.seller
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "6984:5984"
    networks:
      - carbon-net

  # ---------------- CouchDB for Buyer ----------------
  couchdb0.buyer:
    container_name: couchdb0.buyer
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - carbon-net

  couchdb1.buyer:
    container_name: couchdb1.buyer
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    networks:
      - carbon-net

  # ---------------- CouchDB for Regulator ----------------
  couchdb0.regulator:
    container_name: couchdb0.regulator
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"
    networks:
      - carbon-net

  couchdb1.regulator:
    container_name: couchdb1.regulator
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "10984:5984"
    networks:
      - carbon-net

    # ---------------- CA Seller ----------------
  ca.seller.carbon.com:
    container_name: ca.seller.carbon.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-seller
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/seller:/etc/hyperledger/fabric-ca-server
    networks:
      - carbon-net

  # ---------------- CA Buyer ----------------
  ca.buyer.carbon.com:
    container_name: ca.buyer.carbon.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-buyer
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/buyer:/etc/hyperledger/fabric-ca-server
    networks:
      - carbon-net

  # ---------------- CA Regulator ----------------
  ca.regulator.carbon.com:
    container_name: ca.regulator.carbon.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-regulator
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./organizations/fabric-ca/regulator:/etc/hyperledger/fabric-ca-server
    networks:
      - carbon-net

  # ---------------- Seller Peers ----------------
  peer0.seller.carbon.com:
    container_name: peer0.seller.carbon.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-market_carbon-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer0.seller.carbon.com
      - CORE_PEER_ADDRESS=peer0.seller.carbon.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.seller.carbon.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller.carbon.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller.carbon.com:7051
      - CORE_PEER_LOCALMSPID=SellerMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.seller:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0.seller
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/seller.carbon.com/peers/peer0.seller.carbon.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/seller.carbon.com/peers/peer0.seller.carbon.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - carbon-net

  peer1.seller.carbon.com:
    container_name: peer1.seller.carbon.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-market_carbon-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer1.seller.carbon.com
      - CORE_PEER_ADDRESS=peer1.seller.carbon.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.seller.carbon.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.seller.carbon.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller.carbon.com:7051
      - CORE_PEER_LOCALMSPID=SellerMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.seller:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1.seller
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/seller.carbon.com/peers/peer1.seller.carbon.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/seller.carbon.com/peers/peer1.seller.carbon.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 8051:8051
    networks:
      - carbon-net

  # ---------------- Buyer Peers ----------------
  peer0.buyer.carbon.com:
    container_name: peer0.buyer.carbon.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-market_carbon-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer0.buyer.carbon.com
      - CORE_PEER_ADDRESS=peer0.buyer.carbon.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.buyer.carbon.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer.carbon.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer.carbon.com:9051
      - CORE_PEER_LOCALMSPID=BuyerMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.buyer:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0.buyer
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/buyer.carbon.com/peers/peer0.buyer.carbon.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/buyer.carbon.com/peers/peer0.buyer.carbon.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - carbon-net

  peer1.buyer.carbon.com:
    container_name: peer1.buyer.carbon.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-market_carbon-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer1.buyer.carbon.com
      - CORE_PEER_ADDRESS=peer1.buyer.carbon.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.buyer.carbon.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.buyer.carbon.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer.carbon.com:9051
      - CORE_PEER_LOCALMSPID=BuyerMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.buyer:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1.buyer
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/buyer.carbon.com/peers/peer1.buyer.carbon.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/buyer.carbon.com/peers/peer1.buyer.carbon.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 10051:10051
    networks:
      - carbon-net

  # ---------------- Regulator Peers ----------------
  peer0.regulator.carbon.com:
    container_name: peer0.regulator.carbon.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-market_carbon-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer0.regulator.carbon.com
      - CORE_PEER_ADDRESS=peer0.regulator.carbon.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regulator.carbon.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulator.carbon.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulator.carbon.com:11051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.regulator:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0.regulator
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/regulator.carbon.com/peers/peer0.regulator.carbon.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/regulator.carbon.com/peers/peer0.regulator.carbon.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - carbon-net

  peer1.regulator.carbon.com:
    container_name: peer1.regulator.carbon.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=carbon-market_carbon-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer1.regulator.carbon.com
      - CORE_PEER_ADDRESS=peer1.regulator.carbon.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.regulator.carbon.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.regulator.carbon.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulator.carbon.com:11051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.regulator:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1.regulator
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/regulator.carbon.com/peers/peer1.regulator.carbon.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/regulator.carbon.com/peers/peer1.regulator.carbon.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 12051:12051
    networks:
      - carbon-net

  # ---------------- CLI ----------------
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.13
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.seller.carbon.com:7051
      - CORE_PEER_LOCALMSPID=SellerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.carbon.com/peers/peer0.seller.carbon.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/seller.carbon.com/users/Admin@seller.carbon.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/channel-artifacts
    networks:
        - carbon-net

